name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        resolution-strategy: ["highest", "lowest-direct"]

    name: Python ${{ matrix.python-version }} (resolution=${{ matrix.resolution-strategy }})

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: |
          uv sync --python ${{ matrix.python-version }} --resolution ${{ matrix.resolution-strategy }} --all-extras

      - name: Lint package
        run: uv run poe lint

      - name: Test package
        run: uv run poe test
